language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
before_install:
    - sudo apt-get install torque-server torque-client torque-mom torque-pam
    - sudo ./test/setup_torque.sh
install:
    - pip install .
before_script:
    - pip install -r test/requirements_test.txt
script:
    #- coverage run --source payu test_payu.py
    - coverage run --source payu bin/payu
after_success:
    - coverage report -m
    - coveralls
#sudo: False
