{% set data = load_setup_py_data(setup_file='../setup.py') %}
{% set version = data.get('version') %}

package:
    name: payu
    version: "{{ version }}"

build:
    noarch: python
    number: 0
    script: "{{ PYTHON }}  -m pip install . -vv"

source:
  url: "https://pypi.io/packages/source/p/payu/payu-{{ version }}.tar.gz"

requirements:
    host:
        - python
        - pip
        - versioneer
    run:
        - python >=3.9
        - f90nml >=0.16
        - yamanifest >=0.3.4
        - PyYAML
        - requests[security]
        - python-dateutil
        - tenacity!=7.0.0
        - cftime
        - GitPython >=3.1.40
        - ruamel.yaml >=0.18.5

test:
    imports:
        - payu
    commands:
        - payu list

about:
    home: https://github.com/payu-org/payu/
    license: Apache Software
    license_family: APACHE
    summary: "A climate model workflow manager for supercomputing environments"
    doc_url: https://payu.readthedocs.io/en/latest/
